### ISSUE TITLE
Web demo broken

### ISSUE THREAD

**Issue by ppfranco** [SenatoDellaRepubblica/PArSe#1]
La web demo (https://www.senato.it/japp/serv/parse/app) restituisce errore cliccando trasforma, senza ulteriori indicazioni e log:
![errore_parse](https://github.com/SenatoDellaRepubblica/PArSe/assets/10577923/64174978-e30f-4a16-92f4-a902422a795a)

**Comment by RobertoBattistoni** [comment]
Grazie. Controlliamo.

**Comment by RobertoBattistoni** [comment]
Ripristinato il servizio. Chiudo la issue
